import { useEffect, useState } from 'react';
import { Menu, Ticket, X } from 'lucide-react';
import { Link, NavLink, Outlet, useLocation } from 'react-router-dom';
import { camcomexLogo, horizontalLogo } from '../../assets/brand';
import { FacebookIcon, InstagramIcon, YoutubeIcon } from '../icons/SocialIcons';

const nav=[['/sobre-expojuy','La expo'],['/expositores','Expositores'],['/agenda','Agenda'],['/novedades','Novedades'],['/mapa','Mapa'],['/sponsors','Sponsors'],['/contacto','Contacto']];
export function Layout(){const[open,setOpen]=useState(false);const[scrolled,setScrolled]=useState(false);const location=useLocation();useEffect(()=>{setOpen(false);window.scrollTo({top:0,behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'})},[location.pathname]);useEffect(()=>{const onScroll=()=>setScrolled(window.scrollY>20);onScroll();addEventListener('scroll',onScroll,{passive:true});return()=>removeEventListener('scroll',onScroll)},[]);useEffect(()=>{if(typeof IntersectionObserver==='undefined'){document.querySelectorAll('.reveal-group').forEach(el=>el.classList.add('is-revealed'));return;}const observer=new IntersectionObserver((entries)=>{entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-revealed');observer.unobserve(entry.target);}});},{threshold:0.08,rootMargin:'0px 0px -30px 0px'});const observe=()=>{document.querySelectorAll('.reveal-group:not(.is-revealed)').forEach(el=>observer.observe(el));};observe();const t1=setTimeout(observe,80);const t2=setTimeout(observe,300);return()=>{clearTimeout(t1);clearTimeout(t2);observer.disconnect();};},[location.pathname]);return <>
 <a className="skip-link" href="#contenido">Saltar al contenido</a>
 <header className={`site-header ${scrolled?'is-scrolled':''}`}><div className="nav-wrap">
  <Link to="/" className="brand" aria-label="ExpoJuy 2026, inicio"><img src={horizontalLogo} alt="ExpoJuy 2026" width={2614} height={1125} /></Link>
  <nav className="desktop-nav" aria-label="Navegación principal">{nav.map(([to,label])=><NavLink key={to} to={to}>{label}</NavLink>)}</nav>
  <Link className="header-cta" to="/entradas"><Ticket size={18}/>Conseguí tu entrada</Link>
  <button className="menu-button" aria-label={open?'Cerrar menú':'Abrir menú'} aria-expanded={open} onClick={()=>setOpen(x=>!x)}>{open?<X/>:<Menu/>}</button>
 </div>{open&&<nav className="mobile-nav" aria-label="Navegación móvil">{nav.map(([to,label])=><NavLink key={to} to={to}>{label}</NavLink>)}<Link className="btn btn-primary" to="/entradas">Conseguí tu entrada</Link></nav>}</header>
 <main id="contenido"><Outlet/></main>
 <footer className="footer"><div className="container footer-grid"><div><img src={horizontalLogo} alt="ExpoJuy 2026" width={2614} height={1125}/><p>Una plataforma de encuentro para el desarrollo productivo, la tecnología y el talento del Norte Argentino.</p><div className="organizer"><span>Institución impulsora</span><img src={camcomexLogo} alt="Cámara de Comercio Exterior de Jujuy" width={1077} height={1008}/></div></div><div><h2>Explorá</h2><Link to="/agenda">Agenda</Link><Link to="/expositores">Expositores</Link><Link to="/preguntas-frecuentes">Preguntas frecuentes</Link><Link to="/entradas">Conseguí tu entrada</Link></div><div><h2>Contacto</h2><a href="mailto:contacto@expojuy.com.ar">contacto@expojuy.com.ar</a><p>San Salvador de Jujuy, Argentina</p><div className="socials"><a href="https://instagram.com" target="_blank" rel="noopener noreferrer" aria-label="Instagram"><InstagramIcon size={18}/></a><a href="https://facebook.com" target="_blank" rel="noopener noreferrer" aria-label="Facebook"><FacebookIcon size={18}/></a><a href="https://youtube.com" target="_blank" rel="noopener noreferrer" aria-label="YouTube"><YoutubeIcon size={18}/></a></div></div></div><div className="footer-bottom">© {new Date().getFullYear()} ExpoJuy 2026</div></footer>
 </>}
