import { ArrowRight, Atom, Building2, CalendarDays, Cpu, Factory, Gem, Globe2, Leaf, Map, Sparkles, Users } from 'lucide-react';
import { Link } from 'react-router-dom';
import { activities, exhibitors, sectorsList, sponsors } from '../data/content';
import { news } from '../data/news';
import { Badge, LinkButton, SectionHeading } from '../components/ui';
import { camcomexLogo, isologo } from '../assets/brand';
import { Countdown } from '../components/Countdown';
const icons=[Gem,Leaf,Globe2,Cpu,Building2,Atom,Factory,Sparkles];
export function HomePage(){return <>
 <section className="hero"><div className="hero-grid container"><div className="hero-copy"><p className="eyebrow">EXPOSICIÓN PRODUCTIVA Y EMPRESARIAL · PROPUESTA 2026</p><h1>El futuro se encuentra <em>acá.</em></h1><p>Jujuy conecta producción, empresas, innovación y conocimiento para proyectar una región que avanza con identidad propia.</p><div className="button-row"><LinkButton to="/entradas" variant="light">Conseguí tu entrada <ArrowRight/></LinkButton><LinkButton to="/agenda" variant="secondary">Explorar la agenda</LinkButton><LinkButton to="/expositores" variant="secondary">Conocer expositores</LinkButton></div></div><div className="hero-orbit" aria-label="Información demostrativa del evento"><div className="orbit-mark"><img src={isologo} alt="Isologotipo de ExpoJuy 2026" width={1510} height={1509}/></div><div className="date-card"><CalendarDays/><div><small>FECHA DEMOSTRATIVA</small><strong>15—17 OCT · 2026</strong><span>Predio por confirmar · Jujuy</span></div></div><Countdown/></div></div></section>
 <section className="stats container" aria-label="Indicadores demostrativos">{[['120+','Expositores estimados'],['45','Actividades demo'],['8','Sectores productivos'],['15K','Visitantes proyectados']].map(x=><div key={x[1]}><strong>{x[0]}</strong><span>{x[1]}</span></div>)}</section>
 <section className="section home-about"><div className="container split"><div><SectionHeading eyebrow="SOBRE LA EXPOSICIÓN" title="Una vidriera para el talento y la producción de Jujuy" copy="ExpoJuy 2026 se proyecta como un punto de encuentro entre quienes producen, innovan, investigan, invierten y construyen comunidad."/><LinkButton to="/sobre-expojuy" variant="secondary">Conocer la propuesta</LinkButton></div><div className="key-values" aria-label="Valores de la propuesta">{['Innovación','Tecnología','Producción','Desarrollo','Vinculación empresarial','Economía del conocimiento'].map((value,index)=><div key={value}><span>0{index+1}</span><strong>{value}</strong></div>)}</div></div></section>
 <section className="section"><div className="container"><SectionHeading eyebrow="UN TERRITORIO EN MOVIMIENTO" title="Todo lo que Jujuy produce. Todo lo que puede transformar." copy="Una experiencia para descubrir capacidades, construir vínculos y convertir ideas en desarrollo."/><div className="sector-grid">{sectorsList.map((s,i)=>{const Icon=icons[i];return <Link to={`/expositores?sector=${encodeURIComponent(s)}`} className="sector-card" key={s}><span><Icon/></span><h3>{s}</h3><ArrowRight/></Link>})}</div></div></section>
 <section className="section section-tint"><div className="container"><SectionHeading eyebrow="AGENDA ABIERTA" title="Conversaciones que mueven la región"/><div className="agenda-list">{activities.slice(0,4).map(a=><article key={a.id}><time>{a.time}</time><div><Badge>{a.category}</Badge><h3>{a.title}</h3><p>{a.speakers.join(' · ')} — {a.location}</p></div><Link aria-label={`Ver ${a.title}`} to="/agenda"><ArrowRight/></Link></article>)}</div><LinkButton to="/agenda">Ver agenda completa</LinkButton></div></section>
 <section className="section"><div className="container"><SectionHeading eyebrow="QUIÉNES HACEN" title="Un ecosistema productivo conectado"/><div className="logo-grid">{exhibitors.slice(0,6).map(e=><div key={e.id}><span>{e.name.slice(0,2).toUpperCase()}</span><strong>{e.name}</strong><small>{e.sector}</small></div>)}</div><LinkButton to="/expositores" variant="secondary">Explorar expositores</LinkButton></div></section>
 <section className="map-teaser section"><div className="container split"><div><SectionHeading eyebrow="ORIENTATE" title="Un predio pensado para encontrarse" copy="Explorá pabellones, auditorios, servicios y áreas de experiencia en nuestro plano conceptual."/><LinkButton to="/mapa">Explorar mapa <Map/></LinkButton></div><div className="mini-map" aria-hidden="true"><span className="zone z1">INNOVACIÓN</span><span className="zone z2">EXPOSITORES</span><span className="zone z3">AUDITORIO</span><span className="zone z4">SERVICIOS</span></div></div></section>
 <section className="section"><div className="container"><SectionHeading eyebrow="NOVEDADES" title="Lo que empieza a suceder"/><div className="news-grid">{news.slice(0,3).map((n,i)=><article className={i===0?'featured':''} key={n.id}><div className="news-art"><span>0{i+1}</span></div><Badge>{n.category}</Badge><time>{n.date}</time><h3>{n.title}</h3><p>{n.excerpt}</p><Link to={`/novedades/${n.id}`}>Leer nota <ArrowRight/></Link></article>)}</div></div></section>
 <section className="sponsor-strip"><div className="container"><p>Impulsan esta propuesta</p><div><img className="camcomex-mark" src={camcomexLogo} alt="Cámara de Comercio Exterior de Jujuy" width={1077} height={1008}/>{sponsors.slice(1,5).map(s=><span key={s.id}>{s.name}</span>)}</div><Link to="/sponsors">Quiero ser sponsor →</Link></div></section>
 <section className="final-cta"><div className="container"><Users/><div><p className="eyebrow">VOS TAMBIÉN SOS PARTE</p><h2>El próximo encuentro empieza hoy.</h2></div><div className="button-row"><LinkButton to="/entradas" variant="light">Conseguí tu entrada</LinkButton><LinkButton to="/contacto?tipo=expositor" variant="secondary">Quiero exponer</LinkButton></div></div></section>
 </>}
